first implementation
zenaton/zenaton-javascript pull request #48
Opened 2019-07-10 14:30 UTC by jalric

2019-07-10 14:45 UTC, jalric commented on src/async/Scheduler/Scheduler.js
> +
Should probably accept also a TaskDefinition object.

2019-07-10 14:45 UTC, jalric commented on src/async/Scheduler/Scheduler.js
> +
Should probably accept also a WorkflowDefinition object.

2019-07-18 17:15 UTC, geomagilles requested changes
Request changes mainly following RFC changes

2019-07-18 17:15 UTC, geomagilles commented on src/async/Scheduler/Scheduler.js
> +  constructor(job) {
`Schedule` instead of `Scheduler`? 
An action verb is more natural here

2019-07-18 17:15 UTC, geomagilles commented on src/async/Scheduler/Scheduler.js
> +    this.job = TaskDefinition(taskName);
look at new RFC version: task(name, data)

2019-07-18 17:15 UTC, geomagilles commented on src/async/Scheduler/Scheduler.js
> +  workflow(workflowName) {
look at new RFC version: workflow(name, data)

2019-07-18 17:15 UTC, geomagilles commented on src/async/Scheduler/Scheduler.js
> +  with(...args) {
no need

2019-07-18 17:15 UTC, geomagilles commented on src/async/Scheduler/Scheduler.js
> +    // todo: implement
no need

2019-07-18 17:15 UTC, geomagilles commented on src/async/Scheduler/TaskDefinition.js
> +  constructor(name) {
useless class as far as I understand

2019-07-18 17:15 UTC, geomagilles commented on src/async/Scheduler/WorkflowDefinition.js
> +  constructor(name) {
useless class as far as I understand

2019-08-28 21:15 UTC, closed without merging